name = "pota-web"
main = "src/index.ts"
compatibility_date = "2026-04-24"

workers_dev = false
routes = [
  "w0arr.com/pota-stats",
  "w0arr.com/pota-stats/*",
]

[[r2_buckets]]
binding = "R2"
bucket_name = "pota-data"

[assets]
directory = "dist"
binding = "ASSETS"

[observability]
enabled = true
